### ISSUE TITLE
Molebox compiled exe?

### ISSUE THREAD

**Issue by holidaycoder** [sudachen/Molebox#4]
Hello out there,
is there a url to download a _compiled_ Molebox exe?
I'm a only a vb.net hobby developer and have no chance to get the C code compiled, but really would like to try out Molebox ...
Any help would be appreciated, thank you!
holidaycoder

**Comment by Xitano** [comment]
I also like...
I am an enthusiastic programmer, but I tried to compile the Molebox source and it has many compilation errors!
if possible, please provide us with a compiled version!

**Comment by 0xh3LL0** [comment]
i also have the same problem, provide us with a compiled exe would be helpful...

edit:
nvm, i found the compiled exe, its under release...

**Comment by 0xh3LL0** [comment]
nvm, i found the compiled exe, its under release...

**Comment by holidaycoder** [comment]
Hi 0xh3LL0,
thanks a lot for pointing to release | molebox_gpl.zip, which contains compiled exe!

**Comment by jbeitz107** [comment]
I know this has long been closed but, has anyone successfully compiled this version of molebox? If so please share the steps to make it possible. Thank you
